//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18449
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPFriend.Prompit.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XPFriend.Prompit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] bootstrap_min_css {
            get {
                object obj = ResourceManager.GetObject("bootstrap_min_css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] bootstrap_min_js {
            get {
                object obj = ResourceManager.GetObject("bootstrap_min_js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] bootstrap_theme_min_css {
            get {
                object obj = ResourceManager.GetObject("bootstrap_theme_min_css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Exception occurred: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExceptionOccurred {
            get {
                return ResourceManager.GetString("ExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] glyphicons_halflings_regular_eot {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_eot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] glyphicons_halflings_regular_svg {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_svg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] glyphicons_halflings_regular_ttf {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] glyphicons_halflings_regular_woff {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regular_woff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] index_css {
            get {
                object obj = ResourceManager.GetObject("index_css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   The file format is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidFileFormat {
            get {
                return ResourceManager.GetString("InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] jquery_min_js {
            get {
                object obj = ResourceManager.GetObject("jquery_min_js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Reading &quot;{0}&quot;... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Markdown files (*.md, *.txt)|*.md;*.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScenarioFileDialogFilter {
            get {
                return ResourceManager.GetString("ScenarioFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TestResult {
            get {
                return ResourceManager.GetString("TestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;table&gt;&lt;tr&gt;&lt;td class=&apos;nb&apos;&gt;☑&lt;/td&gt;&lt;td&gt;Tests:&lt;/td&gt;&lt;td class=&apos;num&apos;&gt;{0}&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&apos;eb&apos;&gt;☒&lt;/td&gt;&lt;td&gt;Errors:&lt;/td&gt;&lt;td class=&apos;num&apos;&gt;{1}&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&apos;fb&apos;&gt;☒&lt;/td&gt;&lt;td&gt;Failures:&lt;/td&gt;&lt;td class=&apos;num&apos;&gt;{2}&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;Time:&lt;/td&gt;&lt;td class=&apos;num&apos;&gt;{3}&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;ul&gt;&lt;li&gt;&lt;a href=&apos;{4}&apos; title=&apos;{4}&apos; target=&apos;prompit&apos;&gt;Report File&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TestSummary {
            get {
                return ResourceManager.GetString("TestSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If the test failed, write details of the incident here. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTipsOfCommentField {
            get {
                return ResourceManager.GetString("ToolTipsOfCommentField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close this application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTipsOfFinishButton {
            get {
                return ResourceManager.GetString("ToolTipsOfFinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTipsOfReloadButton {
            get {
                return ResourceManager.GetString("ToolTipsOfReloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Take a screenshot. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTipsOfScreenshotButton {
            get {
                return ResourceManager.GetString("ToolTipsOfScreenshotButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unchecked. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Unchecked {
            get {
                return ResourceManager.GetString("Unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Untested. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Untested {
            get {
                return ResourceManager.GetString("Untested", resourceCulture);
            }
        }
    }
}
